---
sudo: false
language: go
go:
  - 1.4
  - tip
env:
  global:
  - PATH="$HOME/bin:$PATH:$HOME/gopath/bin/"
before_install:
- go get https://github.com/constabulary/gb/...
install:
- gb build ./...
before_script:
- git clone https://github.com/sstephenson/bats.git
- cd bats && ./install.sh $HOME
script:
- gb test ./...
- bats test
notifications:
  email: jesse.szwedko@gmail.com
