sudo: false
language: go
go:
- 1.7.1
install:
- go get github.com/mitchellh/gox
- git clone https://github.com/sstephenson/bats.git /tmp/bats && /tmp/bats/install.sh $HOME
before_script:
- export PATH="$PATH:$HOME/bin:$GOPATH/bin:$TRAVIS_BUILD_DIR/bin"
- go install $(go list ./... | grep -v '/vendor/')
script:
- go test $(go list ./... | grep -v '/vendor/')
- bats -t test
before_deploy:
- GOPATH=$PWD:$PWD/vendor gox -os 'linux windows darwin' -arch '386 amd64' -output 'dist/{{.OS}}_{{.Arch}}/{{.Dir}}' git-duet/...
- for build in $(find dist/* -type d) ; do tar cvzf $build.tar.gz -C $build . ; done
deploy:
  provider: releases
  api_key:
    secure: dr5caFZ1Vv5wiSnusBEpD8yrUO4JfbILT52itfzInG/VXmCxvfkpvhPshmwFAaHdKaGJTqshfMQwvBkL2GRwTP1D1rRzS113I6XlxaX1MXU1yUR7QDoujYndri915Vraw5LnXT9GsMjsKIr9WSFyV7XxYMqMklZIWbuTbwDnlF/2+2RxLqSuC8My647Ff+OZwAXdGgeebI7zJX+q8TiwaHXWTX2qoiuP33VwPGxaD7hKkkyIqW2XTpqWEP61t5K5M+bqoCvaOPaYHNsNspQLG/pGqvQ/epbfinBWZC/JaB+Qg1dsFz0tDws5lwLkNxNWmVC6jf/WFcLxH15fDumBh14DHbw6mZfYdICxBBj98c24nBFw14/aVVPEOKVpaTvp1AyQa8flpCbFjhi+/sibuqigP9Pw1C6YtrWUHVJzG6gcrvk+KLYp8vT3eNvI75rkUdXB8ZM1NQPMxlhJ9UWj8fW1FJmeACAeGK3gB1tKumwz1EqtljrXfEiTwCTh/Ntc/+9g37+QrxTkBSSZ0um/lihRtYb+NLIlz5WOn7n81BeMl54HkWyBmfvedc74skgNKRHYDcQFkoriqckLOq9Jz+iZWNporUP2JlJ8a78mSEQ92JWqIGP8+FtB/vBDc7bzdUh9hOOKkfCRIukKrTDPWaO7XzVLcZ8aKAeG8D+IISs=
  file_glob: true
  file: 'dist/*.tar.gz'
  skip_cleanup: true
  on:
    repo: git-duet/git-duet
    tags: true
notifications:
  email: jesse.szwedko@gmail.com
