sudo: false
language: go
go:
- 1.7.1
install:
- go get github.com/constabulary/gb/...
- go get github.com/mitchellh/gox
- git clone https://github.com/sstephenson/bats.git /tmp/bats && /tmp/bats/install.sh $HOME
before_script:
- export PATH="$PATH:$HOME/bin:$GOPATH/bin:$TRAVIS_BUILD_DIR/bin"
- gb build ./...
script:
- gb test ./...
- bats -t test
before_deploy:
- GOPATH=$PWD:$PWD/vendor gox -os 'linux windows darwin' -arch '386 amd64' -output 'dist/{{.OS}}_{{.Arch}}/{{.Dir}}' git-duet/...
- for build in $(find dist/* -type d) ; do tar cvzf $build.tar.gz -C $build . ; done
deploy:
  provider: releases
  api_key:
    secure: kbMX7hp8Fx4FSS4et4XsHkCCAa7rHvy3ZIjZe5ATMmLXGSh11g0FHq8jGue6Mnu6rDmDmeVc1h74VA7f9vqdYTqfxmEAKsQvV+oJLvqg29tvY/6B5GuyVSRatKM0r3QPKOqlhLYGnsI9LT995gzPQBywgucg0DGDqURxgx0yr9WdUYNnlxJ/rcJCcF7mNpI1/R3R7PJejcUHw8bxzHqqGw6JHd3cDhNFXUwZIl7Bsy5s9MdiQrNz+pFzkRC0N2wN8LY2cN3hI/odSshhqZHuJnXQKQIq+S0PVhJHMBdrAZi+dLmPCXUYwI9wsv9n8JGcKNVYYhPK65anbYMXuZV4szoSVYV2JhuWixjFsO7u6WUb2lAJYkekJSzwt7EcpvWG6ouR65Oz+Gw8awp+FOyJ7BXPMXWCNNtU2fn47GCbN/sPeKbazEOCMbv5+LdxNV+hh7zgyEl+w+DbgGtltaJWI5aNZBLyqqXjoyqBklV7FHBCodWJZpzQEOe+3yBm1mKnLoMa0Ru+0WDgLDk0uRU1sIgG164lnINaJ1pI52TaSRI77QkWRtkdGiRdUIVtWF2gWa9evqY3PEb37ZdP0eDvHo7cOEi8ZFj7sJy3nMg3Y7qXq3mf0GmB5whfEdpd2dh0qplMzUy83vabj+wvbbHzCCMc7ltEyCfd5wHhfuRpe6A=
  file_glob: true
  file: 'dist/*.tar.gz'
  skip_cleanup: true
  on:
    repo: git-duet/git-duet
    tags: true
notifications:
  email: jesse.szwedko@gmail.com
